//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类Mall_Admin。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mall_Admin")]
    [Serializable]
    public partial class Mall_Admin : Entity
    {
        #region Model
        private int _Admin_UID;
        private string _Admin;
        private string _Admin_Name;
        private int _Type;
        private string _Passwrod;
        private string _IP;
        private DateTime? _Login_Time;
        private string _Invitation_Code;
        private int _State;
        private string _Remarks;

        /// <summary>
        /// 
        /// </summary>
        [Field("Admin_UID")]
        public int Admin_UID
        {
            get { return _Admin_UID; }
            set
            {
                this.OnPropertyValueChange("Admin_UID");
                this._Admin_UID = value;
            }
        }
        /// <summary>
        /// 账户
        /// </summary>
        [Field("Admin")]
        public string Admin
        {
            get { return _Admin; }
            set
            {
                this.OnPropertyValueChange("Admin");
                this._Admin = value;
            }
        }
        /// <summary>
        /// 名字
        /// </summary>
        [Field("Admin_Name")]
        public string Admin_Name
        {
            get { return _Admin_Name; }
            set
            {
                this.OnPropertyValueChange("Admin_Name");
                this._Admin_Name = value;
            }
        }
        /// <summary>
        /// 类型
        /// </summary>
        [Field("Type")]
        public int Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 密码
        /// </summary>
        [Field("Passwrod")]
        public string Passwrod
        {
            get { return _Passwrod; }
            set
            {
                this.OnPropertyValueChange("Passwrod");
                this._Passwrod = value;
            }
        }
        /// <summary>
        /// 登录IP
        /// </summary>
        [Field("IP")]
        public string IP
        {
            get { return _IP; }
            set
            {
                this.OnPropertyValueChange("IP");
                this._IP = value;
            }
        }
        /// <summary>
        /// 登录时间
        /// </summary>
        [Field("Login_Time")]
        public DateTime? Login_Time
        {
            get { return _Login_Time; }
            set
            {
                this.OnPropertyValueChange("Login_Time");
                this._Login_Time = value;
            }
        }
        /// <summary>
        /// 邀请码
        /// </summary>
        [Field("Invitation_Code")]
        public string Invitation_Code
        {
            get { return _Invitation_Code; }
            set
            {
                this.OnPropertyValueChange("Invitation_Code");
                this._Invitation_Code = value;
            }
        }
        /// <summary>
        /// 状态
        /// </summary>
        [Field("State")]
        public int State
        {
            get { return _State; }
            set
            {
                this.OnPropertyValueChange("State");
                this._State = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Remarks")]
        public string Remarks
        {
            get { return _Remarks; }
            set
            {
                this.OnPropertyValueChange("Remarks");
                this._Remarks = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Admin_UID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Admin_UID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Admin_UID,
                _.Admin,
                _.Admin_Name,
                _.Type,
                _.Passwrod,
                _.IP,
                _.Login_Time,
                _.Invitation_Code,
                _.State,
                _.Remarks,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Admin_UID,
                this._Admin,
                this._Admin_Name,
                this._Type,
                this._Passwrod,
                this._IP,
                this._Login_Time,
                this._Invitation_Code,
                this._State,
                this._Remarks,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mall_Admin");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Admin_UID = new Field("Admin_UID", "Mall_Admin", "");
            /// <summary>
			/// 账户
			/// </summary>
			public readonly static Field Admin = new Field("Admin", "Mall_Admin", "账户");
            /// <summary>
			/// 名字
			/// </summary>
			public readonly static Field Admin_Name = new Field("Admin_Name", "Mall_Admin", "名字");
            /// <summary>
			/// 类型
			/// </summary>
			public readonly static Field Type = new Field("Type", "Mall_Admin", "类型");
            /// <summary>
			/// 密码
			/// </summary>
			public readonly static Field Passwrod = new Field("Passwrod", "Mall_Admin", "密码");
            /// <summary>
			/// 登录IP
			/// </summary>
			public readonly static Field IP = new Field("IP", "Mall_Admin", "登录IP");
            /// <summary>
			/// 登录时间
			/// </summary>
			public readonly static Field Login_Time = new Field("Login_Time", "Mall_Admin", "登录时间");
            /// <summary>
			/// 邀请码
			/// </summary>
			public readonly static Field Invitation_Code = new Field("Invitation_Code", "Mall_Admin", "邀请码");
            /// <summary>
			/// 状态
			/// </summary>
			public readonly static Field State = new Field("State", "Mall_Admin", "状态");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remarks = new Field("Remarks", "Mall_Admin", "备注");
        }
        #endregion
    }
}